### ISSUE TITLE
Random note from search seems to be broken under v. 0.9.19

### ISSUE THREAD

**Issue by base-I** [erichalldev/obsidian-smart-random-note#10]
Random note works, however random note from search does not work. Icon in the banner on the left does not show up. I have updated to the latest version of the plugin.

**Comment by erichalldev** [comment]
Thanks for the report, @base-I. You're on plugin version 0.1.3, right? This shouldn't matter, but which operating system are you using? Does the command "Open Random Note from Search" show up in the command palette?

**Comment by base-I** [comment]
But I tried to replicate it now but no issues what so ever...

Maybe a restart of obsidian fixed the issue, but right after updating the plugin to 0.1.3 neither the dice in the command palette showed up nor was the hotkey working. I cleared the hotkey and set a different one. I am on MacOS 10.15.7

Sorry for wasting your time on this. I can't say for certain whether this was a user error or not.

**Comment by erichalldev** [comment]
No worries! There may be a bug that happens when it's updated. I haven't thoroughly tested that scenario.

**Comment by base-I** [comment]
I encountered the same problem again with an hotkey not related to your plugin. A restart of Obsidian fixed the issue, hence my confusion about the bug report.
