### ISSUE TITLE
Instead of opening, paste a link to random note at current cursor position

### ISSUE THREAD

**Issue by radebrecht** [erichalldev/obsidian-smart-random-note#13]
I want to use the feature for a solo-rpg, with tagged notes as random events. I don't need to read the note, but I want a link to it in my current story, so that the randomized event is documented.

**Comment by erichalldev** [comment]
Thank you for the feedback! I'm sorry it took so long to get back to you. This is a really cool idea! I love the creativity. I'll add this to the feature queue.

**Comment by erichalldev** [comment]
I implemented this feature in release 0.2.2. Happy RPG-ing!
