### ISSUE TITLE
Feature Request -- Exclude Directory

### ISSUE THREAD

**Issue by tallguyjenks** [erichalldev/obsidian-smart-random-note#2]
**Use case:** Ignoring a file path OR multiple file paths. To ignore daily notes, templates, and other folders for plugin files from the
- daily notes 
- template
- day planner

plugins :)

**Comment by erichalldev** [comment]
In version 0.1.1 you can open a note from the list of search results. This unlocks the power of the core search plugin to create the list from which to pull a random note. This includes the ability to ignore file paths. Happy randomizing!

**Comment by tallguyjenks** [comment]
Yes! i just chained a bunch of ignores for both paths and tags and saved the search, that meets the need for my use case and the opening in new leaf is \*chefs kiss\* great work!
