### ISSUE TITLE
Open random daily note

### ISSUE THREAD

**Issue by berdan** [erichalldev/obsidian-smart-random-note#3]
A nice feature would be the ability to open a random daily note, from the location specified in the Daily notes core plugin.

**Comment by tallguyjenks** [comment]
@berdan you can do that if you run a search for `path:"name of your daily notes folder here"` and use this plugin :)

**Comment by erichalldev** [comment]
Thanks @tallguyjenks.

@berdan I'm trying to reuse as much core functionality as possible, so this is the way to do it.
