### ISSUE TITLE
feature request: set excluded folders

### ISSUE THREAD

**Issue by rklasen** [erichalldev/obsidian-smart-random-note#6]
Hi, thanks for this plugin!

I often use the "random note" feature to review old notes, update them etc. But there are some folders that I wish to exclude, because the notes either don't need revisions or are deliberately reviewed with the Review Plugin.

Is there an option to excluce some folders from the pool of random notes?

Best wishes

**Comment by tallguyjenks** [comment]
@rklasen you can do a search like this:

`path:-"Journal" AND path:-"Templates" AND -tag:#⚙️ AND -tag:#🗺️`

to exclude an endless amount of things, and then save that search in obsidian so you can just click your saved search then use the plugin, at least that's my current workflow with it

**Comment by erichalldev** [comment]
Thanks for the quick response, @tallguyjenks.

@rklasen, I'm trying to reuse as much core functionality as possible, so this is the way to do it.

**Comment by rklasen** [comment]
I see, this works for me :smiley:

( I neglected to see in the closed issues before posting, I now see that's already the third or so time someone asks)

Thanks!
